export_client: True
export_server: False

refresh_only: False
update_bcc_version: True
cleanup_temp: True
create_release_notes: True
server_mods_remove_list: []
print_path_debug: True
update_publish_workflow: True
download_compare_files: True
generate_primary_changelog: True
generate_mods_changelog: True

bh_banner: ""

repo_owner: "CrismPack"
repo_name: ""